# -*- coding: utf-8 -*-
"""iris_ds.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13hGX1PHcaowXV_y24dlPsIQsu1nYXYmk
"""

import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import pickle
import json
import requests

# read iris df
iris = pd.read_csv('Iris.csv')
print(iris.head())

print(iris.dtypes)

plt.hist(iris['Species'])
print(plt.show)

le = LabelEncoder()
le.fit(iris['Species'])

iris['Species'] = le.transform(iris['Species'])

print(iris.head())

# features
X = iris.iloc[:,1:5]
print(X.head())

y = iris.iloc[:,5]
print(y.head())

# split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 123)

# Algorithm and Model
algo = DecisionTreeClassifier()
model = algo.fit(X_train, y_train)

# preds 
preds = model.predict(X_test)

# check accuracy 
print("Accuracy Score: ", accuracy_score(y_test, preds))

# this report shows precision, recall, and f1-score 
print("CLassification report: ", classification_report(y_test, preds))

#pickle
pickle.dump(model, open('iris_model.pkl', 'wb'))

url = "http://localhost:9000/api"

data = json.dumps({'SepalLengthCm': 7, 'SepalWidthCm': 3.5,
                  'PetalLengthCm': 4.7, 'PetalWidthCm': 1.4})

print("Data: ", data)

# post(where, what)
send = requests.post(url, data)
# ERROR HERE
print(send)