"""empty message

Revision ID: 43739554e67f
Revises: 
Create Date: 2020-05-18 23:40:00.579918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43739554e67f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
